### ISSUE TITLE
When using another language, buttons flash briefly to english when opening Widget

### ISSUE THREAD

**Issue by nealg1** [Rise-Vision/common-i18n#31]
<b>How it works now:</b> 
Set your operating sytsem/browser to use another language (I used french)
Open a Presentation and add the test Calendar Widget (for example, this was also seen with the test versions of the HTML, Text, Earnings Widget, along with the production Financial Table.)
Click on Configuration

Notice after the settings open, there is a flash where the buttons change from french to english, and then back to french.

<b>How it should work</b>
The flash noticed above should not happen, buttons should remain french.

**Comment by alex-deaconu** [comment]
@nealg1 I've implemented a fix for this in the financial-table widget. Can you check out this URL: https://s3.amazonaws.com/widget-financial-table-test/0.1.0/dist/settings.html
and let me know if you see an improvement. Thanks.

**Comment by nealg1** [comment]
@alex-deaconu It still happens, but if this is the best that can be done, I wouldn't be too worried about it.  It is really a minor thing in my opinion.

**Comment by alanclayton** [comment]
@alex-deaconu Unless you have a quick fix I don't think we need to worry about now. What do you think?

**Comment by alex-deaconu** [comment]
@alanclayton agreed. Thanks.

**Comment by ByronDarlison** [comment]
@alanclayton @alex-deaconu is this issue still open? Thanks

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QdJYk0XO&#x2F;1105-issues-common-i18n-5-open"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issues: common-i18n {5 open}</a>

**Comment by alex-deaconu** [comment]
@ByronDarlison my best guess is it is still occurring; I haven't tested this in a while however. Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu okay. Let's address as part of an epic that will go after the international market after we get through our current known epics. Thanks
